### ISSUE TITLE
Can't Upload images

### ISSUE THREAD

**Issue by vseager** [outeredge/magento-menu-module#21]

**Comment by broopdias** [comment]
Can't reproduce, all seems fine with image upload locally.
Can you clarify?

![screenshot-customer-noodoll bruno-noodoll dev edge-servers com-2019 01 24-13-03-26](https://user-images.githubusercontent.com/2809478/51680023-7fdb8280-1fd8-11e9-8b0f-d9b11e8c49a6.png)
